export default [
  {
    image: "src/routes/projects/img-file/project-newyear.png",
    des: "New year counter project. This project were made with JS and React with some CSS.",
    live: "https://sharifhafizi.github.io/Christmas-Countdown/",
    github: "https://github.com/SharifHafizi/Christmas-Countdown.git",
    gitlogo: "src/routes/projects/img-file/githubSmal.png",
  },
  {
    image: "src/routes/projects/img-file/weatherApp.png",
    des: "This Project is made with Vite, JS, Tailwind CSS and used API to fetch data for the weather forecast.",
    live: "https://sharifhafizi.github.io/Weather-App/",
    github: "https://github.com/SharifHafizi/Weather-App",
    gitlogo: "src/routes/projects/img-file/githubSmal.png",
  },
  {
    image: "src/routes/projects/img-file/Solar-System-Project.png",
    des: "Solar system projetcs which is purely made just with HTML and CSS. It was my first project after learning html and css.",
    live: "https://sharifhafizi.github.io/space-project-main/",
    github: "https://github.com/SharifHafizi/space-project-main",
    gitlogo: "src/routes/projects/img-file/githubSmal.png",
  },
  {
    image: "src/routes/projects/img-file/Pokedex.png",
    des: "Pokedex projects is maded with JS and CSS. In this project we learned how to use API and fetch data.",
    live: "https://sharifhafizi.github.io/Api-Pokedex/",
    github: "https://github.com/SharifHafizi/Api-Pokedex",
    gitlogo: "src/routes/projects/img-file/githubSmal.png",
  },
  {
    image: "src/routes/projects/img-file/CSS-3D.png",
    des: "This is a 3D image veiwer with animation which is purely made in CSS.",
    live: "https://sharifhafizi.github.io/CSS-3D/",
    github: "https://github.com/SharifHafizi/CSS-3D",
    gitlogo: "src/routes/projects/img-file/githubSmal.png",
  },
  {
    image: "src/routes/projects/img-file/RandomPass.png",
    des: " This Project is made in JS and CSS which generate strong password for the user safety.",
    live: "https://sharifhafizi.github.io/Random-pass/",
    github: "https://github.com/SharifHafizi/Random-pass",
    gitlogo: "src/routes/projects/img-file/githubSmal.png",
  },
  {
    image: "src/routes/projects/img-file/converter.png",
    des: " This Project is made in JS and CSS which converts different unites.",
    live: "https://sharifhafizi.github.io/Unit-converter/",
    github: "https://github.com/SharifHafizi/Unit-converter",
    gitlogo: "src/routes/projects/img-file/githubSmal.png",
  },
  {
    image: "src/routes/projects/img-file/DrumKitJS.png",
    des: "Drumkit Project which is purely made with javaScript. It works very fine and is ready to use as tablets or mobile apps. Internal CSS applied.",
    live: "https://sharifhafizi.github.io/Drum-Kit-JS/",
    github: "https://github.com/SharifHafizi/Drum-Kit-JS.git",
    gitlogo: "src/routes/projects/img-file/githubSmal.png",
  },
];
